// Code generated by go generate ./internal/genodfxml; DO NOT EDIT.

package ods

import (
	"encoding/xml"
	"fmt"
)

func (c Content) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "office:document-content"
	addODFAttrOmitEmpty(&start, "xmlns:office", c.Office)
	addODFAttrOmitEmpty(&start, "xmlns:table", c.Table)
	addODFAttrOmitEmpty(&start, "xmlns:text", c.Text)
	addODFAttrOmitEmpty(&start, "xmlns:style", c.Style)
	addODFAttrOmitEmpty(&start, "xmlns:fo", c.FO)
	addODFAttrOmitEmpty(&start, "xmlns:svg", c.SVG)
	addODFAttrOmitEmpty(&start, "xmlns:number", c.Number)
	addODFAttrOmitEmpty(&start, "xmlns:meta", c.MetaNS)
	addODFAttrOmitEmpty(&start, "xmlns:dc", c.DC)
	addODFAttrOmitEmpty(&start, "xmlns:of", c.Of)
	addODFAttrOmitEmpty(&start, "xmlns:calcext", c.Calcext)
	addODFAttrOmitEmpty(&start, "office:version", c.Version)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	if c.Scripts != nil {
		if err := e.EncodeElement(c.Scripts, xml.StartElement{Name: xml.Name{Local: "office:scripts"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if err := e.EncodeElement(c.FontFaceDecls, xml.StartElement{Name: xml.Name{Local: "office:font-face-decls"}}); err != nil {
		return fmt.Errorf("failed to encode element: %w", err)
	}
	if err := e.EncodeElement(c.AutomaticStyles, xml.StartElement{Name: xml.Name{Local: "office:automatic-styles"}}); err != nil {
		return fmt.Errorf("failed to encode element: %w", err)
	}
	if err := e.EncodeElement(c.Body, xml.StartElement{Name: xml.Name{Local: "office:body"}}); err != nil {
		return fmt.Errorf("failed to encode element: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (b Body) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "office:body"
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	if err := e.EncodeElement(b.Spreadsheet, xml.StartElement{Name: xml.Name{Local: "office:spreadsheet"}}); err != nil {
		return fmt.Errorf("failed to encode element: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (s Spreadsheet) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "office:spreadsheet"
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	if s.CalculationSettings != nil {
		if err := e.EncodeElement(s.CalculationSettings, xml.StartElement{Name: xml.Name{Local: "table:calculation-settings"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	for _, value := range s.Table {
		if err := e.EncodeElement(value, xml.StartElement{Name: xml.Name{Local: "table:table"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if s.NamedExpressions != nil {
		if err := e.EncodeElement(s.NamedExpressions, xml.StartElement{Name: xml.Name{Local: "table:named-expressions"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	return e.EncodeToken(start.End())
}

func (f FontFaceDecls) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "office:font-face-decls"
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	if len(f.FontFace) > 0 {
		for _, value := range f.FontFace {
			if err := e.EncodeElement(value, xml.StartElement{Name: xml.Name{Local: "style:font-face"}}); err != nil {
				return fmt.Errorf("failed to encode element: %w", err)
			}
		}
	}
	return e.EncodeToken(start.End())
}

func (f FontFace) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "style:font-face"
	addODFAttrOmitEmpty(&start, "style:name", f.Name)
	addODFAttrOmitEmpty(&start, "svg:font-family", f.FontFamily)
	addODFAttrOmitEmpty(&start, "style:font-family-generic", f.FontFamilyGeneric)
	addODFAttrOmitEmpty(&start, "style:font-pitch", f.FontPitch)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (c CalculationSettings) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "table:calculation-settings"
	addODFAttrOmitEmpty(&start, "table:automatic-find-labels", c.AutomaticFindLabels)
	addODFAttrOmitEmpty(&start, "table:use-regular-expressions", c.UseRegularExpressions)
	addODFAttrOmitEmpty(&start, "table:use-wildcards", c.UseWildcards)
	addODFAttrOmitEmpty(&start, "table:null-year", c.NullYear)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (t Table) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "table:table"
	addODFAttrOmitEmpty(&start, "table:name", t.Name)
	addODFAttrOmitEmpty(&start, "table:style-name", t.StyleName)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	if len(t.TableColumn) > 0 {
		for _, value := range t.TableColumn {
			if err := e.EncodeElement(value, xml.StartElement{Name: xml.Name{Local: "table:table-column"}}); err != nil {
				return fmt.Errorf("failed to encode element: %w", err)
			}
		}
	}
	if len(t.TableRow) > 0 {
		for _, value := range t.TableRow {
			if err := e.EncodeElement(value, xml.StartElement{Name: xml.Name{Local: "table:table-row"}}); err != nil {
				return fmt.Errorf("failed to encode element: %w", err)
			}
		}
	}
	return e.EncodeToken(start.End())
}

func (t TableColumn) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "table:table-column"
	addODFAttrOmitEmpty(&start, "table:style-name", t.StyleName)
	addODFAttrOmitEmpty(&start, "table:number-columns-repeated", t.NumberColumnsRepeated)
	addODFAttrOmitEmpty(&start, "table:default-cell-style-name", t.DefaultCellStyleName)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (t TableRow) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "table:table-row"
	addODFAttrOmitEmpty(&start, "table:style-name", t.StyleName)
	addODFAttrOmitEmpty(&start, "table:number-rows-repeated", t.NumberRowsRepeated)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	if len(t.TableCell) > 0 {
		for _, value := range t.TableCell {
			if err := e.EncodeElement(value, xml.StartElement{Name: xml.Name{Local: "table:table-cell"}}); err != nil {
				return fmt.Errorf("failed to encode element: %w", err)
			}
		}
	}
	return e.EncodeToken(start.End())
}

func (t TableCell) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "table:table-cell"
	addODFAttrOmitEmpty(&start, "table:style-name", t.StyleName)
	addODFAttrOmitEmpty(&start, "office:value-type", t.ValueType)
	addODFAttrOmitEmpty(&start, "calcext:value-type", t.CalcextValueType)
	addODFAttrOmitEmpty(&start, "table:number-columns-repeated", t.NumberColumnsRepeated)
	addODFAttrOmitEmpty(&start, "table:formula", t.Formula)
	addODFAttrOmitEmpty(&start, "office:value", t.Value)
	addODFAttrOmitEmpty(&start, "office:currency", t.Currency)
	addODFAttrOmitEmpty(&start, "office:date-value", t.DateValue)
	addODFAttrOmitEmpty(&start, "office:time-value", t.TimeValue)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	if t.P != "" {
		if err := e.EncodeElement(t.P, xml.StartElement{Name: xml.Name{Local: "text:p"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	return e.EncodeToken(start.End())
}

func (a AutomaticStyles) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "office:automatic-styles"
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	if len(a.Styles) > 0 {
		for _, value := range a.Styles {
			if err := e.EncodeElement(value, xml.StartElement{Name: xml.Name{Local: "style:style"}}); err != nil {
				return fmt.Errorf("failed to encode element: %w", err)
			}
		}
	}
	return e.EncodeToken(start.End())
}

func (s Style) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "style:style"
	addODFAttrOmitEmpty(&start, "style:name", s.Name)
	addODFAttrOmitEmpty(&start, "style:family", s.Family)
	addODFAttrOmitEmpty(&start, "style:parent-style-name", s.ParentStyleName)
	addODFAttrOmitEmpty(&start, "style:master-page-name", s.MasterPageName)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	if s.TableProperties != nil {
		if err := e.EncodeElement(s.TableProperties, xml.StartElement{Name: xml.Name{Local: "style:table-properties"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if s.TableColumnProperties != nil {
		if err := e.EncodeElement(s.TableColumnProperties, xml.StartElement{Name: xml.Name{Local: "style:table-column-properties"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if s.TableRowProperties != nil {
		if err := e.EncodeElement(s.TableRowProperties, xml.StartElement{Name: xml.Name{Local: "style:table-row-properties"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if s.TableCellProperties != nil {
		if err := e.EncodeElement(s.TableCellProperties, xml.StartElement{Name: xml.Name{Local: "style:table-cell-properties"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if s.ParagraphProperties != nil {
		if err := e.EncodeElement(s.ParagraphProperties, xml.StartElement{Name: xml.Name{Local: "style:paragraph-properties"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if s.TextProperties != nil {
		if err := e.EncodeElement(s.TextProperties, xml.StartElement{Name: xml.Name{Local: "style:text-properties"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	return e.EncodeToken(start.End())
}

func (t TableProperties) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "style:table-properties"
	addODFAttrOmitEmpty(&start, "table:display", t.Display)
	addODFAttrOmitEmpty(&start, "style:writing-mode", t.WritingMode)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (t TableColumnProperties) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "style:table-column-properties"
	addODFAttrOmitEmpty(&start, "style:column-width", t.ColumnWidth)
	addODFAttrOmitEmpty(&start, "fo:break-before", t.BreakBefore)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (t TableRowProperties) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "style:table-row-properties"
	addODFAttrOmitEmpty(&start, "style:row-height", t.RowHeight)
	addODFAttrOmitEmpty(&start, "fo:break-before", t.BreakBefore)
	addODFAttrOmitEmpty(&start, "style:use-optimal-row-height", t.UseOptimalRowHeight)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (t TableCellProperties) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "style:table-cell-properties"
	addODFAttrOmitEmpty(&start, "fo:background-color", t.BackgroundColor)
	addODFAttrOmitEmpty(&start, "fo:border", t.Border)
	addODFAttrOmitEmpty(&start, "style:vertical-align", t.VerticalAlign)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (p ParagraphProperties) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "style:paragraph-properties"
	addODFAttrOmitEmpty(&start, "fo:text-align", p.TextAlign)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (t TextProperties) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "style:text-properties"
	addODFAttrOmitEmpty(&start, "fo:color", t.Color)
	addODFAttrOmitEmpty(&start, "fo:font-weight", t.FontWeight)
	addODFAttrOmitEmpty(&start, "style:font-weight-asian", t.FontWeightAsian)
	addODFAttrOmitEmpty(&start, "style:font-weight-complex", t.FontWeightComplex)
	addODFAttrOmitEmpty(&start, "fo:font-style", t.FontStyle)
	addODFAttrOmitEmpty(&start, "style:font-style-asian", t.FontStyleAsian)
	addODFAttrOmitEmpty(&start, "style:font-style-complex", t.FontStyleComplex)
	addODFAttrOmitEmpty(&start, "fo:font-size", t.FontSize)
	addODFAttrOmitEmpty(&start, "fo:font-family", t.FontFamily)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (m Meta) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "office:document-meta"
	addODFAttrOmitEmpty(&start, "xmlns:office", m.Office)
	addODFAttrOmitEmpty(&start, "xmlns:meta", m.MetaNS)
	addODFAttrOmitEmpty(&start, "xmlns:dc", m.DC)
	addODFAttrOmitEmpty(&start, "office:version", m.Version)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	if err := e.EncodeElement(m.Body, xml.StartElement{Name: xml.Name{Local: "office:meta"}}); err != nil {
		return fmt.Errorf("failed to encode element: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (m MetaBody) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "office:meta"
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	if m.Generator != "" {
		if err := e.EncodeElement(m.Generator, xml.StartElement{Name: xml.Name{Local: "meta:generator"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if m.Title != "" {
		if err := e.EncodeElement(m.Title, xml.StartElement{Name: xml.Name{Local: "dc:title"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if m.Subject != "" {
		if err := e.EncodeElement(m.Subject, xml.StartElement{Name: xml.Name{Local: "dc:subject"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if m.Description != "" {
		if err := e.EncodeElement(m.Description, xml.StartElement{Name: xml.Name{Local: "dc:description"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if m.Keywords != "" {
		if err := e.EncodeElement(m.Keywords, xml.StartElement{Name: xml.Name{Local: "meta:keyword"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if m.InitialCreator != "" {
		if err := e.EncodeElement(m.InitialCreator, xml.StartElement{Name: xml.Name{Local: "meta:initial-creator"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if m.Creator != "" {
		if err := e.EncodeElement(m.Creator, xml.StartElement{Name: xml.Name{Local: "dc:creator"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if m.CreationDate != "" {
		if err := e.EncodeElement(m.CreationDate, xml.StartElement{Name: xml.Name{Local: "meta:creation-date"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if m.Date != "" {
		if err := e.EncodeElement(m.Date, xml.StartElement{Name: xml.Name{Local: "dc:date"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if m.Language != "" {
		if err := e.EncodeElement(m.Language, xml.StartElement{Name: xml.Name{Local: "dc:language"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if m.EditingDuration != "" {
		if err := e.EncodeElement(m.EditingDuration, xml.StartElement{Name: xml.Name{Local: "meta:editing-duration"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if m.EditingCycles != "" {
		if err := e.EncodeElement(m.EditingCycles, xml.StartElement{Name: xml.Name{Local: "meta:editing-cycles"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	if err := e.EncodeElement(m.DocumentStatistic, xml.StartElement{Name: xml.Name{Local: "meta:document-statistic"}}); err != nil {
		return fmt.Errorf("failed to encode element: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (d DocumentStatistic) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "meta:document-statistic"
	addODFAttrOmitEmpty(&start, "meta:table-count", d.TableCount)
	addODFAttrOmitEmpty(&start, "meta:cell-count", d.CellCount)
	addODFAttrOmitEmpty(&start, "meta:object-count", d.ObjectCount)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	return e.EncodeToken(start.End())
}

func (m Manifest) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "manifest:manifest"
	addODFAttrOmitEmpty(&start, "xmlns:manifest", m.Xmlns)
	addODFAttrOmitEmpty(&start, "manifest:version", m.Version)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	for _, value := range m.Files {
		if err := e.EncodeElement(value, xml.StartElement{Name: xml.Name{Local: "manifest:file-entry"}}); err != nil {
			return fmt.Errorf("failed to encode element: %w", err)
		}
	}
	return e.EncodeToken(start.End())
}

func (m ManifestFile) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	start.Name.Local = "manifest:file-entry"
	addODFAttr(&start, "manifest:full-path", m.FullPath)
	addODFAttr(&start, "manifest:media-type", m.MediaType)
	if err := e.EncodeToken(start); err != nil {
		return fmt.Errorf("failed to encode token: %w", err)
	}
	return e.EncodeToken(start.End())
}

func addODFAttrOmitEmpty(start *xml.StartElement, name, value string) {
	if value == "" {
		return
	}
	addODFAttr(start, name, value)
}

func addODFAttr(start *xml.StartElement, name, value string) {
	start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: name}, Value: value})
}
