package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"reflect"
	"strconv"
	"strings"
)

type structDef struct {
	Name    string
	Element string
	Fields  []fieldDef
}

type fieldDef struct {
	Name      string
	ODFName   string
	Attr      bool
	OmitEmpty bool
	Kind      fieldKind
}

type fieldKind int

const (
	kindString fieldKind = iota
	kindPointer
	kindSlice
	kindValue
)

func main() {
	typeFile := flag.String("type-file", "xml_types.go", "Go file containing ODF model structs")
	outFile := flag.String("out", "odf_marshal_gen.go", "generated output file")
	flag.Parse()

	defs, err := parseStructs(*typeFile)
	if err != nil {
		fatal(err)
	}
	src, err := render(defs)
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*outFile, src, 0o644); err != nil {
		fatal(err)
	}
}

func parseStructs(path string) ([]structDef, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	var defs []structDef
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		element := odfElement(gen.Doc)
		if element == "" {
			continue
		}
		for _, spec := range gen.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}
			def, err := parseStruct(typeSpec.Name.Name, element, st)
			if err != nil {
				return nil, err
			}
			defs = append(defs, def)
		}
	}
	return defs, nil
}

func odfElement(group *ast.CommentGroup) string {
	if group == nil {
		return ""
	}
	for _, comment := range group.List {
		text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
		if element, ok := strings.CutPrefix(text, "odf:marshal "); ok {
			return strings.TrimSpace(element)
		}
	}
	return ""
}

func parseStruct(name, element string, st *ast.StructType) (structDef, error) {
	def := structDef{Name: name, Element: element}
	for _, field := range st.Fields.List {
		if field.Tag == nil || len(field.Names) == 0 {
			continue
		}
		tag, err := strconv.Unquote(field.Tag.Value)
		if err != nil {
			return def, fmt.Errorf("%s: failed to parse struct tag: %w", name, err)
		}
		odf := reflect.StructTag(tag).Get("odf")
		if odf == "" || odf == "-" {
			continue
		}
		parsed, err := parseField(field.Names[0].Name, odf, field.Type)
		if err != nil {
			return def, fmt.Errorf("%s.%s: %w", name, field.Names[0].Name, err)
		}
		def.Fields = append(def.Fields, parsed)
	}
	return def, nil
}

func parseField(name, tag string, expr ast.Expr) (fieldDef, error) {
	parts := strings.Split(tag, ",")
	if parts[0] == "" {
		return fieldDef{}, fmt.Errorf("odf name is empty")
	}
	field := fieldDef{Name: name, ODFName: parts[0], Kind: exprKind(expr)}
	for _, option := range parts[1:] {
		switch option {
		case "attr":
			field.Attr = true
		case "omitempty":
			field.OmitEmpty = true
		case "":
		default:
			return fieldDef{}, fmt.Errorf("unsupported odf option: %q", option)
		}
	}
	if field.Attr && field.Kind != kindString {
		return fieldDef{}, fmt.Errorf("attribute must be a string")
	}
	return field, nil
}

func exprKind(expr ast.Expr) fieldKind {
	switch value := expr.(type) {
	case *ast.StarExpr:
		return kindPointer
	case *ast.ArrayType:
		return kindSlice
	case *ast.Ident:
		if value.Name == "string" {
			return kindString
		}
		return kindValue
	default:
		return kindValue
	}
}

func render(defs []structDef) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate ./internal/genodfxml; DO NOT EDIT.\n\n")
	buf.WriteString("package ods\n\n")
	buf.WriteString("import (\n\t\"encoding/xml\"\n\t\"fmt\"\n)\n\n")
	for _, def := range defs {
		renderStruct(&buf, def)
	}
	renderHelpers(&buf)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("failed to format generated code: %w", err)
	}
	return formatted, nil
}

func renderStruct(buf *bytes.Buffer, def structDef) {
	receiver := strings.ToLower(def.Name[:1])
	fmt.Fprintf(buf, "func (%s %s) MarshalXML(e *xml.Encoder, start xml.StartElement) error {\n", receiver, def.Name)
	fmt.Fprintf(buf, "\tstart.Name.Local = %q\n", def.Element)
	for _, field := range def.Fields {
		if field.Attr {
			helper := "addODFAttr"
			if field.OmitEmpty {
				helper = "addODFAttrOmitEmpty"
			}
			fmt.Fprintf(buf, "\t%s(&start, %q, %s.%s)\n", helper, field.ODFName, receiver, field.Name)
		}
	}
	fmt.Fprintf(buf, "\tif err := e.EncodeToken(start); err != nil { return fmt.Errorf(\"failed to encode token: %%w\", err) }\n")
	for _, field := range def.Fields {
		if field.Attr {
			continue
		}
		renderChild(buf, receiver, field)
	}
	fmt.Fprintf(buf, "\treturn e.EncodeToken(start.End())\n")
	fmt.Fprintf(buf, "}\n\n")
}

func renderChild(buf *bytes.Buffer, receiver string, field fieldDef) {
	selector := receiver + "." + field.Name
	switch field.Kind {
	case kindString:
		if field.OmitEmpty {
			fmt.Fprintf(buf, "\tif %s != \"\" {\n", selector)
			fmt.Fprintf(buf, "\t\tif err := e.EncodeElement(%s, xml.StartElement{Name: xml.Name{Local: %q}}); err != nil { return fmt.Errorf(\"failed to encode element: %%w\", err) }\n", selector, field.ODFName)
			fmt.Fprintf(buf, "\t}\n")
			return
		}
		fmt.Fprintf(buf, "\tif err := e.EncodeElement(%s, xml.StartElement{Name: xml.Name{Local: %q}}); err != nil { return fmt.Errorf(\"failed to encode element: %%w\", err) }\n", selector, field.ODFName)
	case kindPointer:
		if field.OmitEmpty {
			fmt.Fprintf(buf, "\tif %s != nil {\n", selector)
			fmt.Fprintf(buf, "\t\tif err := e.EncodeElement(%s, xml.StartElement{Name: xml.Name{Local: %q}}); err != nil { return fmt.Errorf(\"failed to encode element: %%w\", err) }\n", selector, field.ODFName)
			fmt.Fprintf(buf, "\t}\n")
			return
		}
		fmt.Fprintf(buf, "\tif err := e.EncodeElement(%s, xml.StartElement{Name: xml.Name{Local: %q}}); err != nil { return fmt.Errorf(\"failed to encode element: %%w\", err) }\n", selector, field.ODFName)
	case kindSlice:
		if field.OmitEmpty {
			fmt.Fprintf(buf, "\tif len(%s) > 0 {\n", selector)
			fmt.Fprintf(buf, "\t\tfor _, value := range %s { if err := e.EncodeElement(value, xml.StartElement{Name: xml.Name{Local: %q}}); err != nil { return fmt.Errorf(\"failed to encode element: %%w\", err) } }\n", selector, field.ODFName)
			fmt.Fprintf(buf, "\t}\n")
			return
		}
		fmt.Fprintf(buf, "\tfor _, value := range %s { if err := e.EncodeElement(value, xml.StartElement{Name: xml.Name{Local: %q}}); err != nil { return fmt.Errorf(\"failed to encode element: %%w\", err) } }\n", selector, field.ODFName)
	case kindValue:
		fmt.Fprintf(buf, "\tif err := e.EncodeElement(%s, xml.StartElement{Name: xml.Name{Local: %q}}); err != nil { return fmt.Errorf(\"failed to encode element: %%w\", err) }\n", selector, field.ODFName)
	}
}

func renderHelpers(buf *bytes.Buffer) {
	buf.WriteString(`func addODFAttrOmitEmpty(start *xml.StartElement, name, value string) {
	if value == "" {
		return
	}
	addODFAttr(start, name, value)
}

func addODFAttr(start *xml.StartElement, name, value string) {
	start.Attr = append(start.Attr, xml.Attr{Name: xml.Name{Local: name}, Value: value})
}
`)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
